version: '3.8'

services:
  frontend:
    image: "ghcr.io/tup-utn-frc-lciii/flight-check-in-front-end"
    build: .
    ports:
      - "4200:4200"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: reverse_proxy
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - "8080:8080"
      - "80:80"
    depends_on:
      - backend
      - frontend


  backend:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/vuelos
      SPRING_DATASOURCE_USERNAME: utn
      SPRING_DATASOURCE_PASSWORD: utn

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: vuelos
      MYSQL_USER: utn
      MYSQL_PASSWORD: utn
      MYSQL_ROOT_PASSWORD: utn
      TZ: America/Argentina/Buenos_Aires #Zona horaria
    ports:
      - "3306:3306"
    expose:
      - "3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
